### ISSUE TITLE
Additional training

### ISSUE THREAD

**Issue by GEkuL** [FSecureLABS/captcha22#18]
Hi, is this possible, to train the already made model with additional sets?

**Comment by TinusGreen** [comment]
Hi GEkuL,

Unfortunately not. AOCR generates a tfRecord at the start of training. The tfRecord keeps all of the images that will be used for training. Once AOCR starts training a model, it calls upon this tfRecord to perform the batch training. By adding new images, the tfRecord is altered, which means the input no longer fits the model being trained, hence training can't resume.

When using GPU-powered training, this isn't really an issue since generating a model takes about 7 minutes. With CPU training however, it does take quite a bit of time to train a new model. But there is no getting around it sadly.

What we have done in the past is something like this:

1. We train a model until we get around 60% training accuracy.
2. By exporting and using this model, we stage a live brute force attack. To improve accuracy, we add a prediction threshold, only submitting the CAPTCHA if our model's prediction is above a certain percentage accuracy (usually anything above 90% gets good results, but sometimes we even restrict it even more to something like 98%).
3. We also take the live CAPTCHA samples from the website and store them to disk. CAPTCHAs we don't submit due to low certainty, we store in a separate folder. Then, for CAPTCHAs that we do submit, we review the response from the application since most will tell you when the CAPTCHA is incorrect. Therefore we split submitted CAPTCHAs into a correct and incorrect folder. The correct folder will therefore contain CAPTCHAs that the automated system labelled itself. 
4. We then just simply add those correctly labelled CAPTCHAs to our existing samples and retrain another model. This is how the system can in essence "train itself"
5. What we also do, is we manually label the CAPTCHAs that were never submitted, since this is "new" data for the system. Letters and numbers that it has not seen as much before to be certain. Which if you provide more samples, usually drastically increase the training accuracy. 

Using this process, we have been able to train models that hit submission accuracies of up to 99% and training accuracy of more than 90%.

Hope this helps, but sadly there is no getting away from training a new model from scratch once you add new samples.
