### ISSUE TITLE
Issues on following the readme

### ISSUE THREAD

**Issue by piliugin-anton** [FSecureLABS/captcha22#20]
Please add the folowing information to readme file:
Required Python version 3.7 (tensorflow 1.15.5 - current, requires it)
After labelling we need to rename a ZIP file in the next format <username>_<captcha_name>_<captcha_version>.zip

**Comment by TinusGreen** [comment]
Closed with f5e2662f64cbb4d2606982a1b1d0a449a081631f.

**Comment by piliugin-anton** [comment]
The tool that generates ZIP file doesn't name it correctly, it creates a data.zip file

**Comment by TinusGreen** [comment]
Hi piliugin-anton,

The renaming occurs through the API client when the file is uploaded. The intended use for captcha22 is to create a cracking server and host an API to interface with it. Then using the client API to interact with this server. It is this API that requests the captcha name from the user and will automatically attach the correct version after interfacing with the server. 

This version cannot be known by the labelling script as it does not interface with the server, which is why this was not implemented. If you wish to not use the API, you can just add a final `name = str(raw_input("Enter file name:"))` into your version of the labelling script and use that to rename the file.
