### ISSUE TITLE
Some problem

### ISSUE THREAD

**Issue by vladverbiy** [FSecureLABS/captcha22#3]
![1](https://user-images.githubusercontent.com/49246796/86533717-b579e000-bedb-11ea-843b-157ef7945905.png)

**Comment by TinusGreen** [comment]
Hi vladverbiy,

This seems to be an issue with the virtual environments.

See here: https://github.com/pypa/pipenv/issues/3824 and https://github.com/pypa/virtualenv/issues/228

The virtualenv creates its own copies of the captcha22 packages which is why it can't find the main sitepackages that it needs.

Sitepackages are inherently used in captcha22. This is used to find and import all relevant captcha22 scripts into the primary script. Also since the virtualenv copies the scripts to a random location each time, it is not possible to hard code a solution.

Could you please try to run the script without a virtualenv or attempt the fixes mentioned in the above issues?
